; ============================================================================
; VoiceBack Smart Neckband Firmware - PlatformIO Configuration
; Target MCU: ESP32 Development Board (ESP-WROOM-32  ESP32-D0WDQ6)
; ============================================================================

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = COM7
upload_speed = 460800

; Serial Monitor Speed
monitor_speed = 115200

; MCU Performance Settings
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = dio
board_build.partitions = huge_app.csv
lib_archive = no

; Library Dependencies
lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3
    h2zero/NimBLE-Arduino @ ^1.4.1

